version: '3.8'
services:
  ollama:
    image: ollama/ollama:rocm
    container_name: ollama
    restart: ${RESTART_POLICY:-unless-stopped}
    ports:
      - "127.0.0.1:11434:11434" 
    volumes:
      - ${OLLAMA_DATA_PATH}:/root/.ollama:Z 
    environment:
      - OLLAMA_LLM_LIBRARY=rocm
      - HSA_OVERRIDE_GFX_VERSION=${OLLAMA_HSA_VERS}
    devices:
      - "/dev/dri:/dev/dri"
      - "/dev/kfd:/dev/kfd"
    resources:
         limits:
           cpus: '7.5'
           memory: 60G
         reservations:
           memory: 30G
    security_opt:
      - label=disable
    cap_add:
      - SYS_PTRACE
